from enum import StrEnum


class ProviderStatus(StrEnum):
    PASS = "PASS"
    PARTIAL = "PARTIAL"
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
    NOT_AVAILABLE = "NOT_AVAILABLE"
    NETWORK_ERROR = "NETWORK_ERROR"
    TIMEOUT = "TIMEOUT"
    RATE_LIMITED = "RATE_LIMITED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    ACCESS_DENIED = "ACCESS_DENIED"
    SOURCE_CHANGED = "SOURCE_CHANGED"
    PARSE_ERROR = "PARSE_ERROR"
    CONTENT_UNAVAILABLE = "CONTENT_UNAVAILABLE"
    PDF_UNAVAILABLE = "PDF_UNAVAILABLE"
    LEGAL_UNCLEAR = "LEGAL_UNCLEAR"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


TERMINAL_FAILURES = {
    ProviderStatus.AUTH_REQUIRED,
    ProviderStatus.ACCESS_DENIED,
    ProviderStatus.NOT_AVAILABLE,
}
