from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import pandas as pd

from .capability import redact_text
from .models import CapabilityRecord, MetricResult, QualityIssue, SpikeContext


def write_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def capability_summary(records: list[CapabilityRecord]) -> dict[str, Any]:
    counts = Counter(record.status for record in records)
    by_api: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        by_api[record.api_name].append(
            {
                "capability": record.capability,
                "status": record.status,
                "row_count": record.row_count,
                "latest_date": record.latest_date,
                "impacts_features": record.impacts_features,
            }
        )

    return {
        "status_counts": dict(counts),
        "apis": dict(by_api),
        "provider_recommendation": provider_recommendation(records),
        "minimum_permissions_to_confirm": minimum_permissions(records),
        "fallback_summary": fallback_summary(records),
    }


def provider_recommendation(records: list[CapabilityRecord]) -> str:
    critical_apis = {"trade_cal", "stock_basic", "daily", "daily_basic", "adj_factor", "index_daily"}
    successful = {record.api_name for record in records if record.api_name in critical_apis and record.status == "PASS"}
    denied = {record.api_name for record in records if record.status == "PERMISSION_DENIED"}

    if critical_apis.issubset(successful):
        if {"sw_daily", "anns_d"}.intersection(denied):
            return "Tushare is a possible first provider for core daily-market data, but announcement or industry-index permissions must be resolved before formal adoption."
        return "Tushare is a possible first provider candidate, pending product-owner review and permission confirmation."
    return "Tushare should not be promoted to formal provider until critical daily-market capabilities pass."


def minimum_permissions(records: list[CapabilityRecord]) -> list[str]:
    needed = []
    for api_name in [
        "trade_cal",
        "stock_basic",
        "daily",
        "daily_basic",
        "adj_factor",
        "suspend_d",
        "index_daily",
        "index_member_all",
        "sw_daily",
        "anns_d",
        "rt_min_daily",
    ]:
        api_records = [record for record in records if record.api_name == api_name]
        if not api_records:
            continue
        if any(record.status in {"PERMISSION_DENIED", "RATE_LIMITED", "INVALID_REQUEST", "API_ERROR"} for record in api_records):
            needed.append(api_name)
    return needed


def fallback_summary(records: list[CapabilityRecord]) -> list[dict[str, str]]:
    rows = []
    for record in records:
        if record.status != "PASS":
            rows.append(
                {
                    "api_name": record.api_name,
                    "capability": record.capability,
                    "status": record.status,
                    "fallback": record.recommended_fallback,
                }
            )
    return rows


def metrics_summary(results: list[MetricResult]) -> dict[str, Any]:
    counts = Counter(result.status for result in results)
    by_symbol = defaultdict(Counter)
    minute_dependent = []
    for result in results:
        by_symbol[result.symbol][result.status] += 1
        if result.metric == "max_intraday_drawdown":
            minute_dependent.append(result.to_dict())
    return {
        "status_counts": dict(counts),
        "by_symbol": {symbol: dict(counter) for symbol, counter in by_symbol.items()},
        "success_count": counts.get("PASS", 0),
        "total_count": len(results),
        "minute_dependent_metrics": minute_dependent,
    }


def quality_summary(issues: list[QualityIssue]) -> dict[str, Any]:
    counts = Counter(issue.status for issue in issues)
    return {
        "status_counts": dict(counts),
        "issues": [issue.to_dict() for issue in issues if issue.status != "PASS"],
    }


def capability_markdown(context: SpikeContext, records: list[CapabilityRecord]) -> str:
    summary = capability_summary(records)
    lines = [
        "# Tushare Capability Report",
        "",
        "This report is generated by an isolated data-feasibility spike. It does not mark Tushare as the final provider.",
        "",
        "## Run Context",
        "",
        f"- Provider: {context.provider}",
        f"- Queried at: {context.queried_at}",
        f"- Shanghai now: {context.shanghai_now}",
        f"- Latest ended trade date: {context.latest_trade_date}",
        f"- Symbols: {', '.join(context.symbols)}",
        f"- Days: {context.days}",
        f"- Percentile window: {context.percentile_window}",
        f"- Optional probes skipped: {context.skipped_optional}",
        "",
        "## Status Counts",
        "",
        json.dumps(summary["status_counts"], ensure_ascii=False),
        "",
        "## Capability Matrix",
        "",
        "| capability | api | status | rows | earliest | latest | impacts | fallback | error |",
        "| --- | --- | --- | ---: | --- | --- | --- | --- | --- |",
    ]
    for record in records:
        lines.append(
            "| "
            + " | ".join(
                [
                    record.capability,
                    record.api_name,
                    record.status,
                    str(record.row_count),
                    record.earliest_date or "",
                    record.latest_date or "",
                    ", ".join(record.impacts_features),
                    record.recommended_fallback,
                    record.permission_or_error_message or "",
                ]
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Decision Questions",
            "",
            f"- Provider candidate recommendation: {summary['provider_recommendation']}",
            f"- Minimum permissions or fixes still needed: {', '.join(summary['minimum_permissions_to_confirm']) or 'none from this run'}",
            "- Minute-dependent metric: max_intraday_drawdown requires rt_min_daily minute close data.",
            "- Daily K, daily returns, historical percentiles and close position depend on daily, daily_basic and adj_factor.",
            "- Industry relative strength requires Shenwan industry membership plus sw_daily; generic index_daily must not be used as a substitute.",
            "- Announcement availability depends on anns_d permission and returned URL metadata.",
            "- Concept/theme availability is optional and depends on tdx_member or another official standard concept member interface.",
        ]
    )
    return "\n".join(lines) + "\n"


def metrics_markdown(context: SpikeContext, results: list[MetricResult]) -> str:
    summary = metrics_summary(results)
    lines = [
        "# Metrics Report",
        "",
        "Metrics are program-calculated from provider data. AI must not generate or backfill these values.",
        "",
        f"- Latest ended trade date: {context.latest_trade_date}",
        f"- Formula version: {results[0].formula_version if results else 'n/a'}",
        f"- Success count: {summary['success_count']} / {summary['total_count']}",
        "",
        "| symbol | metric | status | value | unit | window | as_of_date | missing_reason |",
        "| --- | --- | --- | ---: | --- | --- | --- | --- |",
    ]
    for result in results:
        value = "" if result.value is None else f"{result.value:.6f}"
        lines.append(
            f"| {result.symbol} | {result.metric} | {result.status} | {value} | {result.unit} | {result.window} | {result.as_of_date or ''} | {result.missing_reason or ''} |"
        )
    return "\n".join(lines) + "\n"


def quality_markdown(context: SpikeContext, issues: list[QualityIssue]) -> str:
    summary = quality_summary(issues)
    lines = [
        "# Data Quality Report",
        "",
        f"- Latest ended trade date: {context.latest_trade_date}",
        f"- Status counts: {json.dumps(summary['status_counts'], ensure_ascii=False)}",
        "",
        "| symbol | dataset | check | status | message | affected_dates |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for issue in issues:
        lines.append(
            f"| {issue.symbol} | {issue.dataset} | {issue.check_name} | {issue.status} | {issue.message} | {', '.join(issue.affected_dates)} |"
        )
    return "\n".join(lines) + "\n"


def write_reports(
    *,
    output_dir: Path,
    context: SpikeContext,
    capability_records: list[CapabilityRecord],
    metric_results: list[MetricResult],
    quality_issues: list[QualityIssue],
    sample_summary: pd.DataFrame,
    token: str | None,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    capability_payload = {
        "context": context.to_dict(),
        "summary": capability_summary(capability_records),
        "records": [record.to_dict() for record in capability_records],
    }
    metrics_payload = {
        "context": context.to_dict(),
        "summary": metrics_summary(metric_results),
        "metrics": [result.to_dict() for result in metric_results],
    }
    quality_payload = {
        "context": context.to_dict(),
        "summary": quality_summary(quality_issues),
        "checks": [issue.to_dict() for issue in quality_issues],
    }

    write_json(output_dir / "capability_report.json", capability_payload)
    write_json(output_dir / "metrics_report.json", metrics_payload)
    write_json(output_dir / "data_quality_report.json", quality_payload)
    (output_dir / "capability_report.md").write_text(capability_markdown(context, capability_records), encoding="utf-8")
    (output_dir / "metrics_report.md").write_text(metrics_markdown(context, metric_results), encoding="utf-8")
    (output_dir / "data_quality_report.md").write_text(quality_markdown(context, quality_issues), encoding="utf-8")
    sample_summary.to_csv(output_dir / "sample_summary.csv", index=False, encoding="utf-8")

    assert_no_token(output_dir, token)


def assert_no_token(output_dir: Path, token: str | None) -> None:
    if not token:
        return
    for path in output_dir.glob("*"):
        if path.is_file():
            text = path.read_text(encoding="utf-8", errors="ignore")
            if token in text or redact_text(token, token) != "[REDACTED_TOKEN]":
                raise RuntimeError(f"Token leak check failed for {path.name}")
