from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    SESSION_REQUIRED = "SESSION_REQUIRED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    FORBIDDEN = "FORBIDDEN"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    STOCK_NOT_FOUND = "STOCK_NOT_FOUND"
    WATCHLIST_ITEM_NOT_FOUND = "WATCHLIST_ITEM_NOT_FOUND"
    WATCHLIST_ITEM_ALREADY_EXISTS = "WATCHLIST_ITEM_ALREADY_EXISTS"
    WATCHLIST_LIMIT_EXCEEDED = "WATCHLIST_LIMIT_EXCEEDED"
    GROUP_NOT_FOUND = "GROUP_NOT_FOUND"
    TAG_NOT_FOUND = "TAG_NOT_FOUND"
    AI_PROVIDER_REQUIRED = "AI_PROVIDER_REQUIRED"
    AI_PROVIDER_NOT_FOUND = "AI_PROVIDER_NOT_FOUND"
    AI_PROVIDER_DISABLED = "AI_PROVIDER_DISABLED"
    AI_PROVIDER_AUTH_FAILED = "AI_PROVIDER_AUTH_FAILED"
    AI_PROVIDER_TIMEOUT = "AI_PROVIDER_TIMEOUT"
    AI_PROVIDER_UNAVAILABLE = "AI_PROVIDER_UNAVAILABLE"
    AI_MODEL_NOT_FOUND = "AI_MODEL_NOT_FOUND"
    AI_INVALID_RESPONSE = "AI_INVALID_RESPONSE"
    AI_SCHEMA_VALIDATION_FAILED = "AI_SCHEMA_VALIDATION_FAILED"
    AI_TASK_ALREADY_RUNNING = "AI_TASK_ALREADY_RUNNING"
    INFORMATION_NOT_FOUND = "INFORMATION_NOT_FOUND"
    INFORMATION_CONTENT_REQUIRED = "INFORMATION_CONTENT_REQUIRED"
    INFORMATION_DUPLICATE = "INFORMATION_DUPLICATE"
    INFORMATION_ALREADY_ARCHIVED = "INFORMATION_ALREADY_ARCHIVED"
    CONTENT_FETCH_FAILED = "CONTENT_FETCH_FAILED"
    CONTENT_FETCH_TIMEOUT = "CONTENT_FETCH_TIMEOUT"
    CONTENT_TOO_LARGE = "CONTENT_TOO_LARGE"
    CONTENT_TYPE_NOT_ALLOWED = "CONTENT_TYPE_NOT_ALLOWED"
    CONTENT_EXTRACTION_FAILED = "CONTENT_EXTRACTION_FAILED"
    CONTENT_EXTRACTION_INSUFFICIENT = "CONTENT_EXTRACTION_INSUFFICIENT"
    URL_INVALID = "URL_INVALID"
    URL_PROTOCOL_NOT_ALLOWED = "URL_PROTOCOL_NOT_ALLOWED"
    URL_PRIVATE_ADDRESS_BLOCKED = "URL_PRIVATE_ADDRESS_BLOCKED"
    URL_REDIRECT_BLOCKED = "URL_REDIRECT_BLOCKED"
    STOCK_RELATION_NOT_FOUND = "STOCK_RELATION_NOT_FOUND"
    ENCRYPTION_KEY_REQUIRED = "ENCRYPTION_KEY_REQUIRED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class AppError(Exception):
    def __init__(
        self,
        code: ErrorCode,
        message: str,
        *,
        status_code: int = 400,
        details: dict[str, Any] | list[Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.status_code = status_code
        self.details = details
